const btn = document.getElementById("btn")
let content = document.getElementById("content")
let author = document.getElementById("author")

const quotes = [
    {'quote': "Things work out best for those who make the best of how things work out.", 'author': "~John Wooden"},
    {'quote': "If you want to achieve greatness stop asking for permission.", 'author': "~Anonymous"},
    {'quote': "To live a creative life, we must lose our fear of being wrong.", 'author': "~Anonymous"},
    {'quote': "If you are not willing to risk the usual you will have to settle for the ordinary.", 'author': "~Jim Rohn"},
    {'quote': "Trust because you are willing to accept the risk, not because it's safe or certain.", 'author': "~Anonymous"},
    {'quote': "All our dreams can come true if we have the courage to pursue them.", 'author': "~Walt Disney"},
    {'quote': "Good things come to people who wait, but better things come to those who go out and get them.", 'author': "~Anonymous"},
    {'quote': "If you do what you always did, you will get what you always got.", 'author': "~Anonymous"},
    {'quote': "Success is walking from failure to failure with no loss of enthusiasm.", 'author': "~Winston Churchill"},
    {'quote': "Just when the caterpillar thought the world was ending, he turned into a butterfly.", 'author': "~Elena Hill"},
    {'quote': "Successful entrepreneurs are givers and not takers of positive energy.", 'author': "~Anonymous"},
    {'quote': "Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them.", 'author': "~Vaibhav Shah"},
    {'quote': "Opportunities don't happen, you create them.", 'author': "~Chris Grosser"},
    {'quote': "Try not to become a person of success, but rather try to become a person of value.", 'author': "~Albert Einstein"},
    {'quote': "Great minds discuss ideas; average minds discuss events; small minds discuss people.", 'author': "~Eleanor Roosevelt"},
    {'quote': "I have not failed. I've just found 10,000 ways that won't work.", 'author': "~Thomas A. Edison"},
    {'quote': "If you don't value your time, neither will others. Stop giving away your time and talents- start charging for it.", 'author': "~Kim Garst"},
    {'quote': "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", 'author': "~David Brinkley"},
    {'quote': "No one can make you feel inferior without your consent.", 'author': "~Eleanor Roosevelt"},
    {'quote': "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", 'author': "~Henry Ford"},
    {'quote': "If you're going through hell keep going.", 'author': " ~Winston Churchill"},
    {'quote': "The ones who are crazy enough to think they can change the world, are the ones that do.", 'author': "~Anonymous"},
    {'quote': "Don't raise your voice, improve your argument.", 'author': "~Anonymous"},
    {'quote': "What seems to us as bitter trials are often blessings in disguise.", 'author': "~Oscar Wilde"},
    {'quote': "The meaning of life is to find your gift. The purpose of life is to give it away.", 'author': "~Anonymous"},
    {'quote': "The distance between insanity and genius is measured only by success.", 'author': "~Bruce Feirstein"},
    {'quote': "When you stop chasing the wrong things you give the right things a chance to catch you.", 'author': "~Lolly Daskal"},
    {'quote': "Don't be afraid to give up the good to go for the great.", 'author': "~John D. Rockefeller"},
    {'quote': "No masterpiece was ever created by a lazy artist.", 'author': "~ Anonymous"},
    {'quote': "If you can't explain it simply, you don't understand it well enough.", 'author': "~Albert Einstein"},
    {'quote': "Blessed are those who can give without remembering and take without forgetting.", 'author': "~Anonymous"},
    {'quote': "Do one thing every day that scares you.", 'author': " ~Anonymous"},
    {'quote': "What's the point of being alive if you don't at least try to do something remarkable.", 'author': "~Anonymous"},
    {'quote': "Life is not about finding yourself. Life is about creating yourself.", 'author': "~Lolly Daskal"},
    {'quote': "Nothing in the world is more common than unsuccessful people with talent.", 'author': "~Anonymous"},
    {'quote': "Knowledge is being aware of what you can do. Wisdom is knowing when not to do it.", 'author': "~Anonymous"},
    {'quote': "Your problem isn't the problem. Your reaction is the problem.", 'author': "~Anonymous"},
    {'quote': "You can do anything, but not everything.", 'author': "~Anonymous"},
    {'quote': "Innovation distinguishes between a leader and a follower.", 'author': "~Steve Jobs"},
    {'quote': "Thinking should become your capital asset, no matter whatever ups and downs you come across in your life.", 'author': "~Dr. APJ Kalam"},
    {'quote': "I find that the harder I work, the more luck I seem to have.", 'author': "~Thomas Jefferson"},
    {'quote': "The starting point of all achievement is desire.", 'author': "~Napolean Hill"},
    {'quote': "Success is the sum of small efforts, repeated day-in and day-out.", 'author': "~Robert Collier"},
    {'quote': "All progress takes place outside the comfort zone.", 'author': "~Michael John Bobak"},
    {'quote': "You may only succeed if you desire succeeding; you may only fail if you do not mind failing.", 'author': "~Philippos"},
    {'quote': "Courage is resistance to fear, mastery of fear - not absense of fear.", 'author': "~Mark Twain"},
    {'quote': "Only put off until tomorrow what you are willing to die having left undone.", 'author': "~Pablo Picasso"},
    {'quote': "People often say that motivation doesn't last. Well, neither does bathing - that's why we recommend it daily.", 'author': "~Zig Ziglar"},
    {'quote': "We become what we think about most of the time, and that's the strangest secret.", 'author': "~Earl Nightingale"},
    {'quote': "The only place where success comes before work is in the dictionary.", 'author': "~Vidal Sassoon"},
    {'quote': "I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.", 'author': "~Martha Stewart"},
    {'quote': "It's not what you look at that matters, it's what you see.", 'author': "~Anonymous"},
    {'quote': "The road to success and the road to failure are almost exactly the same.", 'author': "~Colin R. Davis"},
    {'quote': "The function of leadership is to produce more leaders, not more followers.", 'author': "~Ralph Nader"},
    {'quote': "Success is liking yourself, liking what you do, and liking how you do it.", 'author': "~Maya Angelou"},
    {'quote': "As we look ahead into the next century, leaders will be those who empower others.", 'author': "~Bill Gates"},
    {'quote': "A real entrepreneur is somebody who has no safety net underneath them.", 'author': "~Henry Kravis"},
    {'quote': "The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.", 'author': "~Mark Caine"},
    {'quote': "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", 'author': "~Mark Twain"},
    {'quote': "The successful warrior is the average man, with laser-like focus.", 'author': "~Bruce Lee"},
    {'quote': "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", 'author': "~Dale Carnegie"},
    {'quote': "If you genuinely want something, don't wait for it -- teach yourself to be impatient.", 'author': "~Gurbaksh Chahal"},
    {'quote': "Don't let the fear of losing be greater than the excitement of winning.", 'author': "~Robert Kiyosaki"},
    {'quote': "If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you!", 'author': "~T. Harv Eker"},
    {'quote': "Successful people do what unsuccessful people are not willing to doDon't wish it were easier, wish you were better.", 'author': "~Jim Rohn"},
    {'quote': "The number one reason people fail in life is because they listen to their friends, family, and neighbors.", 'author': "~Napoleon Hill"},
    {'quote': "In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it.", 'author': "~Jane Smiley"},
    {'quote': "Success does not consist in never making mistakes but in never making the same one a second time.", 'author': "~George Bernard Shaw"},
    {'quote': "You must expect great things of yourself before you can do them.", 'author': "~Michael Jordan"},
    {'quote': "Motivation is what gets you started. Habit is what keeps you going.", 'author': "~Jim Ryun"},
    {'quote': "People rarely succeed unless they have fun in what they are doing.", 'author': "~Dale Carnegie"},
    {'quote': "There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul.", 'author': "~Ella Wheeler Wilcox"},
    {'quote': "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.", 'author': "~Francis Chan"},
    {'quote': "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", 'author': "~George Lorimer"},
    {'quote': "To be successful you must accept all challenges that come your way. You can't just accept the ones you like.", 'author': "~Mike Gafka"},
    {'quote': "Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others.", 'author': "~John C. Maxwell"},
    {'quote': "Be miserable. Or motivate yourself. Whatever has to be done, it's always your choice.", 'author': "~Wayne Dyer"},
    {'quote': "To accomplish great things, we must not only act, but also dream, not only plan, but also believe.", 'author': "~Anatole France"},
    {'quote': "You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals.", 'author': "~Booker T. Washington"},
    {'quote': "Real difficulties can be overcome; it is only the imaginary ones that are unconquerable.", 'author': "~Theodore N. Vail"},
    {'quote': "It is better to fail in originality than to succeed in imitation.", 'author': "~Herman Melville"},
    {'quote': "Fortune sides with him who dares.", 'author': "~Virgil"},
    {'quote': "Little minds are tamed and subdued by misfortune; but great minds rise above it.", 'author': "~Washington Irving"},
    {'quote': "Failure is the condiment that gives success its flavor.", 'author': "~Truman Capote"},
    {'quote': "Don't let what you cannot do interfere with what you can do.", 'author': "~John R. Wooden"},
    {'quote': "You may have to fight a battle more than once to win it.", 'author': "~Margaret Thatcher"}
]

function fetchdata(){
    x = Math.floor(Math.random() * 86) + 1;
    content.innerHTML = quotes[x-1].quote
    author.innerHTML = quotes[x-1].author
}
